// 30 different languages for rotating "Hello" greetings
export const greetings = [
  { language: "English", text: "Hello" },
  { language: "Spanish", text: "Hola" },
  { language: "French", text: "Bonjour" },
  { language: "German", text: "Hallo" },
  { language: "Italian", text: "Ciao" },
  { language: "Portuguese", text: "Olá" },
  { language: "Russian", text: "Привет" },
  { language: "Japanese", text: "こんにちは" },
  { language: "Chinese", text: "你好" },
  { language: "Korean", text: "안녕하세요" },
  { language: "Arabic", text: "مرحبا" },
  { language: "Hindi", text: "नमस्ते" },
  { language: "Urdu", text: "ہیلو" },
  { language: "Turkish", text: "Merhaba" },
  { language: "Dutch", text: "Hallo" },
  { language: "Swedish", text: "Hej" },
  { language: "Norwegian", text: "Hei" },
  { language: "Danish", text: "Hej" },
  { language: "Finnish", text: "Hei" },
  { language: "Polish", text: "Cześć" },
  { language: "Greek", text: "Γειά σου" },
  { language: "Hebrew", text: "שלום" },
  { language: "Thai", text: "สวัสดี" },
  { language: "Vietnamese", text: "Xin chào" },
  { language: "Indonesian", text: "Halo" },
  { language: "Malay", text: "Hello" },
  { language: "Swahili", text: "Habari" },
  { language: "Czech", text: "Ahoj" },
  { language: "Romanian", text: "Salut" },
  { language: "Hungarian", text: "Helló" },
];
